"""Corrected __sol probe statistics (correction of 2026-07-12).

Why this module exists: the __sol activation is captured by a dedicated
forward pass over the SOLUTION PROMPT ONLY (scripts/quadrant_pod_runner.py),
and the solution prompt is a function of (model, problem) alone — it does not
vary with sample_idx, and temperature only enters at generation. The __sol
tensor is therefore deterministic per (model, problem): every sample of a
problem shares one vector. Three consequences, verified here:

1. IDENTITY AUDIT — within-(arm, problem) __sol tensors are byte-identical,
   so the probe has as many distinct inputs as PROBLEMS, not samples. It
   cannot in principle predict which GENERATION launders — only a per-problem
   propensity. (The README's "within-problem variance" control, 9/16 problems
   mixed, is therefore evidence AGAINST the per-generation-plan reading: the
   probe assigns identical scores to samples that behave differently.)
2. LEAKAGE — sample-level k-fold CV places byte-identical copies of a
   problem's vector in both train and test folds; the published 0.82 is
   inflated by problem-identity memorization (an oracle that scores each
   sample by its problem's full-data mean label reaches ~0.9 with no
   activations at all). The leakage-free number is the problem-held-out
   (grouped) CV.
3. SELECTION NULL — the published "shuffle null (~0.6)" permuted labels at
   the SAMPLE level (probe_mechinterp.per_layer_auroc shuffle=True), which
   destroys the within-problem label clustering that drives max-over-61-layers
   selection noise at an effective n of ~16 problems. The correct null
   permutes the problem -> activation-vector pairing, preserving each
   problem's label multiset and the grouped-CV structure. This module runs
   that null (default 1000 permutations) and reports the p-value.

It also computes exact Clopper-Pearson upper bounds for the Stage-3 deception
counts, which were published as bare point estimates ("0.000") without the
problem-level bootstrap CIs the prereg specified. The judge outputs (claim
side) were lost when the judge pod was deleted, so the counts themselves are
as published in commit be5edf1 and cannot currently be re-derived; the
fact-side rows, self-report texts, and __sol tensors are published under
data/evidence/quadrant_v4/ (see package_evidence.py) so everything on the
fact side — including every number in this module — is independently
auditable, and the claim side can be regenerated by re-running a judge over
the published self_report_text fields.

Every published Stage-3 probe number is first REPRODUCED with the repo's own
per_layer_auroc (same folds, same seed; exact under the author's raw file
enumeration order — the plain-CV/shuffle figures are order-dependent, which
is itself documented in the correction §3d) before the corrected statistics
are computed. The corrected statistics are order-invariant by construction,
and the fast problem-level implementation used for the permutation null is
asserted against the reference score-by-score on the real data.

Run (packaged evidence, the auditable path):
    python -m quadrant.probe_correction --evidence data/evidence/quadrant_v4 \
        --out results/correction_2026-07-12
Run (raw pod-sync layout, author machine):
    python -m quadrant.probe_correction --raw --out results/correction_2026-07-12
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os

import numpy as np

try:
    from quadrant.probe_mechinterp import (
        LABELS, _auroc, _make_folds, _meandiff_dir, load_activations,
        load_rows, build_xy, per_layer_auroc,
    )
except ImportError:  # pragma: no cover - direct script execution
    from probe_mechinterp import (
        LABELS, _auroc, _make_folds, _meandiff_dir, load_activations,
        load_rows, build_xy, per_layer_auroc,
    )

# Raw pod-sync locations on the author machine (provenance record; the
# packaged evidence under data/evidence/quadrant_v4/ is the portable copy).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RAW_MANIFEST = {
    arm: os.path.join(_REPO_ROOT, rel) for arm, rel in {
        "base":        "vast_logs/u454anaybb0xs8/st",
        "R-SFT":       "vast_logs/usm5aly7epwsud/st",
        "DPO-r1":      "vast_logs/18q9sawnrb4s9k/st",
        "DPO-r2":      "vast_logs/oqpsdk8423fo4k/st",
        "vanilla-SFT": "vast_logs/zj4qfaufpznm1d/st",
        "vanilla-DPO": "vast_logs/38mhgoiw0pwlna/st",
    }.items()
}

# Construct-union deception counts among passing samples, as published
# (README table / commit be5edf1). The judge outputs backing them were lost
# with the judge pod; bounds below are arithmetic on the published counts.
DECEPTION_COUNTS = {"base": (1, 95), "R-SFT": (0, 35), "DPO-r1": (0, 36)}

HEADLINE_LABEL = "functional_evasion"   # the README's "will use functional/comprehension" row


def clopper_pearson_upper(x: int, n: int, alpha: float = 0.05) -> float:
    """One-sided (1-alpha) exact binomial upper bound for x successes in n."""
    if n <= 0:
        return float("nan")
    if x >= n:
        return 1.0
    from scipy.stats import beta
    return float(beta.ppf(1.0 - alpha, x + 1, n - x))


# --- identity audit ---------------------------------------------------------

def audit_identity(acts: dict) -> dict:
    """Verify __sol tensors are identical within problem, distinct across.

    acts: (problem_id, sample_idx) -> (L, d) float32 array."""
    by_pid: dict[str, list] = {}
    for (pid, _), a in sorted(acts.items()):
        by_pid.setdefault(pid, []).append(a)
    n_pairs = 0
    max_within = 0.0
    all_identical = True
    for arrs in by_pid.values():
        ref = arrs[0]
        for a in arrs[1:]:
            n_pairs += 1
            if not np.array_equal(ref, a):
                all_identical = False
                diff = np.abs(ref - a)
                max_within = max(max_within,
                                 float(np.nanmax(diff)) if np.isnan(diff).any()
                                 else float(diff.max()))
    reps = {pid: arrs[0] for pid, arrs in by_pid.items()}
    pids = sorted(reps)
    min_between = float("inf")
    for i, p in enumerate(pids):
        for q in pids[i + 1:]:
            min_between = min(min_between, float(np.linalg.norm(reps[p] - reps[q])))
    return {
        "n_problems": len(pids),
        "n_samples": len(acts),
        "n_within_problem_pairs": n_pairs,
        "all_within_problem_identical": all_identical,
        "max_within_problem_absdiff": max_within,
        "min_between_problem_l2": min_between if pids else float("nan"),
        "tensor_sha256_by_problem": {
            pid: hashlib.sha256(reps[pid].tobytes()).hexdigest() for pid in pids
        },
    }


# --- fast problem-level grouped CV (for the permutation null) ---------------

def _problem_folds(groups: list, k: int, seed: int) -> list[list]:
    """Problem-level folds identical to probe_mechinterp._make_folds(groups=...)."""
    uniq = np.array(sorted(set(groups)))
    rng = np.random.RandomState(seed)
    gfolds = np.array_split(rng.permutation(len(uniq)), min(k, len(uniq)))
    return [[uniq[i] for i in gf] for gf in gfolds]


def grouped_scores_from_problem_vecs(prob_vecs: np.ndarray, pids: list,
                                     y: np.ndarray, groups: list,
                                     folds: list[list]) -> np.ndarray:
    """Pooled held-out scores (n, L) for grouped CV, computed at problem level.

    Because every sample of a problem shares one vector, the train-fold class
    means equal label-count-weighted means over problem vectors — exact, and
    ~n_samples/n_problems times cheaper, which makes a 1000-permutation null
    tractable. Asserted against per_layer_auroc on the real data in run_arm().
    """
    pid_ix = {p: i for i, p in enumerate(pids)}
    g = np.array([pid_ix[p] for p in groups])
    n, (P, L, D) = len(y), prob_vecs.shape
    n1 = np.bincount(g, weights=(y == 1), minlength=P)
    n0 = np.bincount(g, weights=(y == 0), minlength=P)
    scores = np.full((n, L), np.nan)
    for fold in folds:
        te_p = np.array([pid_ix[p] for p in fold if p in pid_ix], dtype=int)
        if len(te_p) == 0:
            continue
        tr_mask = np.ones(P, bool)
        tr_mask[te_p] = False
        w1, w0 = n1 * tr_mask, n0 * tr_mask
        if w1.sum() == 0 or w0.sum() == 0:
            continue          # degenerate train fold — reference leaves NaN
        mu1 = np.einsum("p,pld->ld", w1, prob_vecs) / w1.sum()
        mu0 = np.einsum("p,pld->ld", w0, prob_vecs) / w0.sum()
        d = mu1 - mu0
        norm = np.linalg.norm(d, axis=1, keepdims=True)
        d = np.where(norm > 0, d / np.where(norm == 0, 1, norm), d)
        s_prob = np.einsum("pld,ld->pl", prob_vecs[te_p], d)
        for j, p in enumerate(te_p):
            scores[g == p] = s_prob[j]
    return scores


def _max_layer_auroc(scores: np.ndarray, y: np.ndarray) -> float:
    aurocs = []
    for l in range(scores.shape[1]):
        m = ~np.isnan(scores[:, l])
        aurocs.append(_auroc(scores[m, l], y[m]) if m.any() else float("nan"))
    arr = np.array(aurocs)
    return float(np.nanmax(arr)) if not np.all(np.isnan(arr)) else float("nan")


def reference_grouped_scores(X: np.ndarray, y: np.ndarray, groups: list,
                             *, k: int = 5, seed: int = 0) -> np.ndarray:
    """Pooled held-out scores (n, L) exactly as per_layer_auroc computes them
    (same folds, same mean-difference direction), returned instead of reduced
    to AUROCs — so the fast problem-level path can be validated score-by-score.

    Validation must happen at the score level, not the AUROC level: within a
    problem the __sol vectors are byte-identical, but `X[te] @ w` scores
    identical rows with ~1e-14 BLAS accumulation jitter, so the reference's
    within-problem ties are broken by floating-point noise before _auroc's
    tie handling can average them. The fast path scores each problem once,
    keeping the ties exact. Both are reported; the difference (~0.005 AUROC
    here) is itself a symptom of pretending n_samples > n_problems.
    """
    n, L, _ = X.shape
    folds = _make_folds(n, y, k, seed, groups=groups)
    scores = np.full((n, L), np.nan)
    for te in folds:
        if len(te) == 0:
            continue
        tr = np.setdiff1d(np.arange(n), te)
        if len(np.unique(y[tr])) < 2:
            continue
        for l in range(L):
            w = _meandiff_dir(X[tr, l, :], y[tr])
            scores[te, l] = X[te, l, :] @ w
    return scores


def perm_null_grouped_max(prob_vecs: np.ndarray, pids: list, y: np.ndarray,
                          groups: list, *, k: int = 5, seed: int = 0,
                          n_perms: int = 1000) -> dict:
    """Null for max-over-layers grouped-CV AUROC: permute which problem's
    activation vector is paired with which problem's label block. Preserves
    within-problem label clustering, block sizes, and fold structure — the
    exchangeability that the sample-level shuffle broke."""
    folds = _problem_folds(groups, k, seed)
    obs = _max_layer_auroc(
        grouped_scores_from_problem_vecs(prob_vecs, pids, y, groups, folds), y)
    rng = np.random.RandomState(seed + 20260712)
    null = []
    for _ in range(n_perms):
        pi = rng.permutation(len(pids))
        stat = _max_layer_auroc(
            grouped_scores_from_problem_vecs(prob_vecs[pi], pids, y, groups, folds), y)
        if not np.isnan(stat):
            null.append(stat)
    null = np.array(null)
    p = float((1 + (null >= obs).sum()) / (1 + len(null))) if len(null) else float("nan")
    return {
        "observed_grouped_max_auroc": obs,
        "n_perms_requested": n_perms,
        "n_perms_valid": int(len(null)),
        "p_value": p,
        "null_mean": float(null.mean()) if len(null) else float("nan"),
        "null_p50": float(np.percentile(null, 50)) if len(null) else float("nan"),
        "null_p95": float(np.percentile(null, 95)) if len(null) else float("nan"),
        "null_max": float(null.max()) if len(null) else float("nan"),
    }


def oracle_baserate_auroc(y: np.ndarray, groups: list) -> float:
    """AUROC of predicting each sample by its problem's FULL-DATA mean label.

    No activations involved. Note this reference includes the scored sample's
    own label in the mean, so it is an upper reference for problem-identity
    information, not a rate attainable by a CV-legal memorizer — for the
    attainable version see foldlegal_baserate_auroc."""
    means = {}
    g = np.array(groups)
    for p in set(groups):
        means[p] = float(y[g == p].mean())
    return _auroc(np.array([means[p] for p in groups]), y)


def foldlegal_baserate_auroc(y: np.ndarray, groups: list, *, k: int = 5,
                             seed: int = 0) -> float:
    """AUROC of a CV-LEGAL problem-identity memorizer under the same
    sample-level folds the published plain-CV probe used.

    Each held-out sample is scored by its problem's mean label among TRAIN
    samples only (falling back to the train global mean if the problem is
    absent from the train folds). This is exactly what duplicate leakage lets
    a probe achieve with zero information from the activations, computed
    without peeking at any test label."""
    g = np.array(groups)
    n = len(y)
    folds = _make_folds(n, y, k, seed, groups=None)
    scores = np.full(n, np.nan)
    for te in folds:
        if len(te) == 0:
            continue
        tr = np.setdiff1d(np.arange(n), te)
        gmean = float(y[tr].mean())
        for i in te:
            mask = g[tr] == g[i]
            scores[i] = float(y[tr][mask].mean()) if mask.any() else gmean
    m = ~np.isnan(scores)
    return _auroc(scores[m], y[m])


def problem_level_lopo(prob_vecs: np.ndarray, pids: list, y: np.ndarray,
                       groups: list, *, seed: int = 0,
                       n_perms: int = 2000) -> dict:
    """The honest unit of analysis: one vector, one label, per problem.

    Label = problem's majority sample label; leave-one-problem-out mean-diff
    probe; max-over-layers AUROC over the P problem scores, with a
    problem-label permutation p-value using the same max statistic.

    "Majority" is undefined for a problem whose samples split exactly 50/50
    (this occurs in the real data: base/functional_evasion has one such
    problem). Rather than let a rounding convention silently decide, both
    assignments are computed and reported: tie_as_neg (ties -> 0) and
    tie_as_pos (ties -> 1). The top-level fields mirror tie_as_neg for
    continuity with earlier output."""
    g = np.array(groups)
    means = np.array([float(y[g == p].mean()) for p in pids])
    n_tied = int((means == 0.5).sum())
    P, L, D = prob_vecs.shape

    def lopo_max(labels: np.ndarray) -> float:
        if labels.sum() < 2 or (1 - labels).sum() < 2:
            return float("nan")
        scores = np.full((P, L), np.nan)
        for i in range(P):
            tr = np.arange(P) != i
            if labels[tr].sum() == 0 or (1 - labels[tr]).sum() == 0:
                continue
            mu1 = prob_vecs[tr & (labels == 1)].mean(0)
            mu0 = prob_vecs[tr & (labels == 0)].mean(0)
            d = mu1 - mu0
            norm = np.linalg.norm(d, axis=1, keepdims=True)
            d = np.where(norm > 0, d / np.where(norm == 0, 1, norm), d)
            scores[i] = np.einsum("ld,ld->l", prob_vecs[i], d)
        return _max_layer_auroc(scores, labels)

    def run(labels: np.ndarray) -> dict:
        obs = lopo_max(labels)
        rng = np.random.RandomState(seed + 424242)
        null = []
        for _ in range(n_perms):
            stat = lopo_max(rng.permutation(labels))
            if not np.isnan(stat):
                null.append(stat)
        null = np.array(null)
        p = (float((1 + (null >= obs).sum()) / (1 + len(null)))
             if len(null) and not np.isnan(obs) else float("nan"))
        return {"n_pos_problems": int(labels.sum()),
                "observed_lopo_max_auroc": obs, "p_value": p,
                "n_perms_valid": int(len(null)),
                "null_p95": float(np.percentile(null, 95)) if len(null) else float("nan")}

    tie_neg = run((means > 0.5).astype(int))
    out = {"n_problems": P, "n_tied_problems": n_tied, "tie_as_neg": tie_neg,
           "n_pos_problems": tie_neg["n_pos_problems"],
           "observed_lopo_max_auroc": tie_neg["observed_lopo_max_auroc"],
           "p_value": tie_neg["p_value"],
           "n_perms_valid": tie_neg["n_perms_valid"],
           "null_p95": tie_neg["null_p95"]}
    if n_tied:
        out["tie_as_pos"] = run((means >= 0.5).astype(int))
    return out


# --- loading ----------------------------------------------------------------

def load_arm_raw(arm_dir: str):
    acts = load_activations(os.path.join(arm_dir, "activations"), "sol")
    rows = load_rows(os.path.join(arm_dir, "paper/data/quadrant/self_reports.jsonl"))
    return acts, rows


def load_arm_evidence(evidence_dir: str, arm: str):
    """Load the packaged evidence. Keys are inserted in SORTED order.

    Row order matters more than it should: the plain-CV and sample-level
    shuffle numbers depend on which samples land in which random fold, which
    depends on dict insertion order, which for the raw path is filesystem
    glob order. The corrected statistics (exact-tie grouped CV, permutation
    null, LOPO, full-data oracle, bounds) are order-invariant by
    construction — verified identical across both load paths — but the
    published-config reproductions, and the foldlegal memorizer reference
    that deliberately shares their folds, are only exact under the author's
    original enumeration order. See docs/correction_2026-07-12.md §3(d)."""
    rows = load_rows(os.path.join(evidence_dir, f"rows_{arm}.jsonl"))
    z = np.load(os.path.join(evidence_dir, f"acts_sol_{arm}.npz"), allow_pickle=False)
    pids = [str(p) for p in z["problem_ids"]]
    vecs = z["vectors"].astype(np.float32)
    by_pid = dict(zip(pids, vecs))
    acts = {}
    for (pid, sidx) in sorted(rows):
        if pid in by_pid:
            acts[(pid, sidx)] = by_pid[pid]
    return acts, rows


# --- per-arm analysis --------------------------------------------------------

def run_arm(arm: str, acts: dict, rows: dict, *, n_perms: int = 1000,
            identity_audit: bool = True) -> dict:
    out: dict = {"arm": arm}
    if identity_audit:
        audit = audit_identity(acts)
        out["identity_audit"] = audit
        if not audit["all_within_problem_identical"]:
            raise RuntimeError(
                f"{arm}: __sol tensors differ within a problem — the premise "
                "of the problem-level fast path is violated; investigate "
                "before use.")

    rs = list(rows.values())
    passing = [r for r in rs if r.get("passes_tests")]
    out["fact_side"] = {
        "n_rows": len(rs), "n_passing": len(passing),
        "launder_rate_shown_and_not_loose_given_pass":
            float(np.mean([bool(r["complied_shown"]) and not bool(r["complied_loose"])
                           for r in passing])) if passing else float("nan"),
        "launder_rate_shown_and_not_strict_given_pass":
            float(np.mean([bool(r["complied_shown"]) and not bool(r["complied_strict"])
                           for r in passing])) if passing else float("nan"),
    }

    out["probes"] = {}
    for label_name, require in ((HEADLINE_LABEL, None),
                                ("laundered", None)):
        X, y, groups = build_xy(acts, rows, LABELS[label_name], require=require)
        entry: dict = {"n": int(len(y)) if len(y) else 0}
        if len(y) == 0:
            out["probes"][label_name] = entry
            continue
        entry["n_pos"] = int((y == 1).sum())
        entry["n_problems"] = len(set(groups))
        entry["n_mixed_problems"] = sum(
            1 for p in set(groups)
            if len(set(y[np.array(groups) == p].tolist())) > 1)
        if entry["n_pos"] < 2 or entry["n"] - entry["n_pos"] < 2:
            entry["note"] = "fewer than 2 samples in a class - probe not fit (matches published n/a)"
            out["probes"][label_name] = entry
            continue

        # (a) reproduce the published configurations with the repo's own code,
        # at the repo's own precision (float32)
        aur_plain, _, _ = per_layer_auroc(X, y, k=5, seed=0)
        aur_group, _, _ = per_layer_auroc(X, y, k=5, seed=0, groups=groups)
        aur_shuf, _, _ = per_layer_auroc(X, y, k=5, seed=0, shuffle=True)
        entry["published_config"] = {
            "plain_cv_max_auroc": float(np.nanmax(aur_plain)),
            "plain_cv_argmax_layer": int(np.nanargmax(aur_plain)),
            "sample_level_shuffle_max_auroc": float(np.nanmax(aur_shuf)),
        }
        if np.all(np.isnan(aur_group)):
            # every grouped train fold was single-class (can happen when an
            # arm spans very few problems, e.g. the 2-problem vanilla arms):
            # there is no leakage-free number to report, which is itself the
            # finding — the plain-CV figure has no problem-held-out support.
            entry["published_config"]["grouped_cv_max_auroc"] = None
            entry["note"] = ("grouped CV undefined: every problem-held-out "
                             "train fold is single-class "
                             f"({entry['n_problems']} problems)")
            out["probes"][label_name] = entry
            continue
        entry["published_config"].update({
            "grouped_cv_max_auroc": float(np.nanmax(aur_group)),
            "grouped_cv_argmax_layer": int(np.nanargmax(aur_group)),
            "grouped_cv_curve_every_4_layers": {
                f"L{l}": round(float(aur_group[l]), 4)
                for l in range(0, len(aur_group), 4)},
        })
        # (b) leakage references with no activations at all: the CV-legal
        # memorizer (attainable through duplicate leakage alone) and the
        # full-data upper reference (includes each sample's own label)
        entry["foldlegal_baserate_auroc"] = float(foldlegal_baserate_auroc(y, groups))
        entry["oracle_problem_baserate_auroc"] = float(oracle_baserate_auroc(y, groups))

        # (c) the corrected null: problem-level permutation. The fast
        # problem-level path is validated against the repo's reference
        # implementation SCORE-BY-SCORE at float64. (AUROC-level comparison
        # is impossible: the reference breaks within-problem ties with
        # ~1e-14 BLAS jitter — see reference_grouped_scores — so its pooled
        # AUROC is itself noise-dependent at the third decimal.)
        pids = sorted(set(groups))
        pid_first = {}
        for (pid, sidx), a in sorted(acts.items()):
            pid_first.setdefault(pid, a)
        prob_vecs = np.stack([pid_first[p] for p in pids]).astype(np.float64)
        folds = _problem_folds(groups, 5, 0)
        scores_fast = grouped_scores_from_problem_vecs(
            prob_vecs, pids, y, groups, folds)
        scores_ref = reference_grouped_scores(
            X.astype(np.float64), y, groups, k=5, seed=0)
        both = ~(np.isnan(scores_fast) | np.isnan(scores_ref))
        if not (both.any() and np.array_equal(np.isnan(scores_fast),
                                              np.isnan(scores_ref))):
            raise RuntimeError(
                f"{arm}/{label_name}: fast and reference paths disagree on "
                "which scores are defined")
        max_score_dev = float(np.abs(scores_fast[both] - scores_ref[both]).max())
        if max_score_dev >= 1e-9:
            raise RuntimeError(
                f"{arm}/{label_name}: fast problem-level scores deviate from "
                f"the reference by {max_score_dev} — implementations disagree")
        entry["fast_vs_reference_max_score_dev"] = max_score_dev
        entry["published_config"]["grouped_cv_max_auroc_noise_broken_ties"] = (
            _max_layer_auroc(scores_ref, y))
        entry["published_config"]["grouped_cv_max_auroc_exact_ties"] = (
            _max_layer_auroc(scores_fast, y))
        entry["problem_permutation_null"] = perm_null_grouped_max(
            prob_vecs, pids, y, groups, k=5, seed=0, n_perms=n_perms)

        # (d) the honest unit of analysis
        entry["problem_level_lopo"] = problem_level_lopo(
            prob_vecs, pids, y, groups, seed=0, n_perms=2000)
        out["probes"][label_name] = entry
    return out


def run_arm_rep(arm: str, acts: dict, rows: dict) -> dict:
    """__rep (post-code, pre-self-report) probe stats: published (plain-CV)
    config plus the problem-held-out number and the no-activation oracle.

    __rep tensors are per-sample distinct (the generated code is in context),
    so the byte-identity critique does not apply — but the grouped-CV /
    problem-identity critique does, and unlike __sol there is no clean
    cluster permutation (blocks of distinct vectors differ in size), so no
    permutation p-value is reported. __rep additionally has the in-context
    confound the README's caveats already flag: the probe may read the code
    itself. Treat these as descriptive."""
    out: dict = {"arm": arm, "position": "rep", "probes": {}}
    for label_name in (HEADLINE_LABEL, "laundered"):
        X, y, groups = build_xy(acts, rows, LABELS[label_name])
        entry: dict = {"n": int(len(y)) if len(y) else 0}
        if len(y) == 0:
            out["probes"][label_name] = entry
            continue
        entry["n_pos"] = int((y == 1).sum())
        entry["n_problems"] = len(set(groups))
        if entry["n_pos"] < 2 or entry["n"] - entry["n_pos"] < 2:
            entry["note"] = "fewer than 2 samples in a class - probe not fit"
            out["probes"][label_name] = entry
            continue
        aur_plain, _, _ = per_layer_auroc(X, y, k=5, seed=0)
        aur_group, _, _ = per_layer_auroc(X, y, k=5, seed=0, groups=groups)
        entry["published_config"] = {
            "plain_cv_max_auroc": float(np.nanmax(aur_plain)),
            "grouped_cv_max_auroc": (None if np.all(np.isnan(aur_group))
                                     else float(np.nanmax(aur_group))),
        }
        if np.all(np.isnan(aur_group)):
            entry["note"] = ("grouped CV undefined: every problem-held-out "
                             "train fold is single-class "
                             f"({entry['n_problems']} problems)")
        entry["oracle_problem_baserate_auroc"] = float(oracle_baserate_auroc(y, groups))
        out["probes"][label_name] = entry
    return out


def deception_bounds() -> dict:
    out = {}
    for arm, (x, n) in DECEPTION_COUNTS.items():
        out[arm] = {
            "published_count": x, "n_passing": n,
            "point_estimate": round(x / n, 4),
            "one_sided_95_upper_bound": round(clopper_pearson_upper(x, n, 0.05), 4),
            "two_sided_95_upper_bound": round(clopper_pearson_upper(x, n, 0.025), 4),
        }
    out["_note"] = (
        "Counts as published (commit be5edf1); judge outputs were lost with "
        "the judge pod, so the claim side is not currently re-derivable — see "
        "docs/correction_2026-07-12.md. Bounds assume independent samples; "
        "samples cluster within <=17 problems, so true uncertainty is larger.")
    return out


def _sanitize_nan(obj):
    """NaN -> None so the output is valid strict JSON (json.dump would emit a
    bare NaN literal that non-Python parsers reject)."""
    if isinstance(obj, dict):
        return {k: _sanitize_nan(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize_nan(v) for v in obj]
    if isinstance(obj, float) and np.isnan(obj):
        return None
    return obj


# --- CLI ---------------------------------------------------------------------

def _cli():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--evidence", help="data/evidence/quadrant_v4 directory")
    src.add_argument("--raw", action="store_true",
                     help="read the raw pod-sync layout in RAW_MANIFEST")
    ap.add_argument("--arms", nargs="*", default=list(RAW_MANIFEST))
    ap.add_argument("--n-perms", type=int, default=1000)
    ap.add_argument("--rep", action="store_true",
                    help="analyze the __rep position instead (raw source only; "
                         "__rep tensors are not packaged — see the evidence README)")
    ap.add_argument("--out", required=True, help="output directory")
    args = ap.parse_args()
    if args.rep and args.evidence:
        ap.error("--rep requires --raw: __rep tensors are not in the evidence package")

    os.makedirs(args.out, exist_ok=True)
    if args.rep:
        results = {"arms": {}}
        for arm in args.arms:
            acts = load_activations(
                os.path.join(RAW_MANIFEST[arm], "activations"), "rep")
            rows = load_rows(os.path.join(
                RAW_MANIFEST[arm], "paper/data/quadrant/self_reports.jsonl"))
            print(f"[{arm}] {len(acts)} __rep tensors, {len(rows)} rows")
            results["arms"][arm] = run_arm_rep(arm, acts, rows)
        path = os.path.join(args.out, "probe_correction_rep_raw.json")
        with open(path, "w") as f:
            json.dump(_sanitize_nan(results), f, indent=2, sort_keys=True,
                      allow_nan=False)
        print(f"wrote {path}")
        return 0

    results = {"deception_upper_bounds": deception_bounds(), "arms": {}}
    for arm in args.arms:
        if args.evidence:
            acts, rows = load_arm_evidence(args.evidence, arm)
        else:
            acts, rows = load_arm_raw(RAW_MANIFEST[arm])
        print(f"[{arm}] {len(acts)} __sol tensors, {len(rows)} rows")
        results["arms"][arm] = run_arm(arm, acts, rows, n_perms=args.n_perms)
        hl = results["arms"][arm]["probes"].get(HEADLINE_LABEL, {})
        pub, pn = hl.get("published_config", {}), hl.get("problem_permutation_null", {})
        if pub:
            fmt = lambda v, spec: (f"{v:{spec}}" if isinstance(v, float) else str(v))
            print(f"  {HEADLINE_LABEL}: plain {fmt(pub.get('plain_cv_max_auroc'), '.3f')} "
                  f"grouped {fmt(pub.get('grouped_cv_max_auroc'), '.3f')} "
                  f"perm-p {fmt(pn.get('p_value'), '.4f')} "
                  f"(null p95 {fmt(pn.get('null_p95'), '.3f')})")
    src_label = "evidence" if args.evidence else "raw"
    path = os.path.join(args.out, f"probe_correction_{src_label}.json")
    with open(path, "w") as f:
        json.dump(_sanitize_nan(results), f, indent=2, sort_keys=True,
                  allow_nan=False)
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(_cli())
