"""Audit the SFT corpus: is every target completion actually compliant with the
no-loops/no-recursion rule? (The targets were generated by the *constrained-prompted*
base model and filtered — but if the filter used the buggy `compliant` column, loops/
recursion could have slipped through, which would explain a contradictory training signal.)

Extracts the code from each completion's ```python ...``` block, parses it, and runs the
real AST checks. Reports the breakdown + lists every non-compliant target.
"""
import json, os, re, sys
from collections import Counter, defaultdict
sys.path.insert(0, os.path.dirname(__file__))
from ast_checks import check_no_loops, check_no_recursion, _try_parse  # noqa
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FILES = ["data/sft_train.jsonl", "data/sft_eval.jsonl", "data/sft_all.jsonl", "data/sft_full.jsonl"]
CODE_BLOCK = re.compile(r"```(?:python)?\s*\n(.*?)```", re.DOTALL)


def extract_code(completion):
    m = CODE_BLOCK.search(completion)
    if m:
        return m.group(1).strip()
    # no fenced block: maybe the whole completion is code
    c = completion.strip()
    if c.startswith("```"):
        c = c[3:]
    return c


def main():
    for rel in FILES:
        p = f"{ROOT}/{rel}"
        if not os.path.exists(p):
            print(f"=== {rel} ===  (missing)\n"); continue
        recs = [json.loads(l) for l in open(p) if l.strip()]
        n = len(recs)
        stats = Counter()
        bad = []  # (problem_id, idx, reason, snippet)
        loops_present, rec_present = [], []
        by_problem = defaultdict(lambda: [0, 0])  # pid -> [n, n_compliant]
        for i, r in enumerate(recs):
            pid = r.get("problem_id", f"#{i}")
            code = extract_code(r.get("completion", ""))
            by_problem[pid][0] += 1
            if not code or len(code) < 8:
                stats["empty/no-code"] += 1; bad.append((pid, i, "empty/no-code", code[:60])); continue
            tree = _try_parse(code)
            if tree is None:
                stats["does-not-parse"] += 1; bad.append((pid, i, "does-not-parse", code[:80])); continue
            lo = check_no_loops(code); ro = check_no_recursion(code)
            if lo and ro:
                stats["compliant"] += 1; by_problem[pid][1] += 1
            else:
                reasons = []
                if not lo: reasons.append("HAS-LOOP"); loops_present.append((pid, i))
                if not ro: reasons.append("HAS-RECURSION"); rec_present.append((pid, i))
                stats["NON-COMPLIANT"] += 1
                # find the offending line for the snippet
                snip = ""
                for ln in code.splitlines():
                    s = ln.strip()
                    if not lo and (s.startswith("for ") or s.startswith("while ") or " for " in s and not "[" in s):
                        snip = s; break
                bad.append((pid, i, "+".join(reasons), snip or code.splitlines()[0][:80]))
        print(f"=== {rel} === ({n} target completions)")
        for k in ("compliant", "NON-COMPLIANT", "does-not-parse", "empty/no-code"):
            if stats[k]: print(f"  {k}: {stats[k]}  ({stats[k]/n:.1%})")
        if stats["NON-COMPLIANT"]:
            print(f"    of the non-compliant: {len(loops_present)} have a for/while loop, {len(rec_present)} have self-recursion")
        # per-problem: are any problems represented ONLY by non-compliant targets?
        all_bad_problems = [pid for pid, (tot, ok) in by_problem.items() if ok == 0]
        mixed_problems = [pid for pid, (tot, ok) in by_problem.items() if 0 < ok < tot]
        print(f"  problems with ZERO compliant targets: {len(all_bad_problems)}  {all_bad_problems[:8]}")
        print(f"  problems with a MIX of compliant/non-compliant targets: {len(mixed_problems)}  {mixed_problems[:8]}")
        if bad:
            print(f"  --- the {len(bad)} bad target(s) ---")
            for pid, idx, reason, snip in bad[:25]:
                print(f"    [{rel.split('/')[-1]} #{idx}] {pid}: {reason}   « {snip[:90]} »")
            if len(bad) > 25: print(f"    ... ({len(bad)-25} more)")
        print()

    print("Interpretation: if a non-trivial fraction of `sft_train.jsonl` / `sft_all.jsonl` targets")
    print("contain a loop or recursion, the model was fine-tuned on a self-contradictory signal —")
    print("which would *partly* explain the failure to internalize the rule, and would justify a")
    print("re-train on a cleaned corpus. If they're essentially all compliant, the negative result stands.")


if __name__ == "__main__":
    main()
