"""Merge the four cohort label/problem files into one manifest each, plus a
per-cell count summary.

Inputs (all under paper/data/cohort/):
  labels_lcb_medium.jsonl
  labels_lcb_hard.jsonl
  labels_trees.jsonl
  problems_trees.jsonl

Outputs:
  paper/data/cohort/labels_merged.jsonl
  paper/data/cohort/problems_cohort.jsonl   — JOIN of LCB-medium + LCB-hard
                                              problems + tree problems
  paper/data/cohort/COHORT_SUMMARY.md       — 2×2 cell-count summary + IDs
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "paper" / "data" / "cohort"


def _read(path: Path) -> list[dict]:
    if not path.exists(): return []
    with path.open() as f:
        return [json.loads(line) for line in f if line.strip()]


def _bucket(label: dict) -> tuple[str, str]:
    """Return (reducibility, representation) bucket name for the 2×2."""
    red = "irreducible" if label["reducibility_tier"] == "irreducible" else "reducible"
    rep = label["representation"]
    return (red, rep)


def main() -> None:
    lcb_medium = _read(OUT / "labels_lcb_medium.jsonl")
    lcb_hard = _read(OUT / "labels_lcb_hard.jsonl")
    trees = _read(OUT / "labels_trees.jsonl")
    tree_problems = _read(OUT / "problems_trees.jsonl")

    all_labels = lcb_medium + lcb_hard + trees
    merged = OUT / "labels_merged.jsonl"
    with merged.open("w") as f:
        for r in all_labels:
            f.write(json.dumps(r) + "\n")
    print(f"wrote: {merged.relative_to(ROOT)}  (n={len(all_labels)})")

    # For now: problems file is just the tree problems jsonl (LCB problems
    # live in data/problems_lcb.jsonl + data/problems_lcb_hard.jsonl). The
    # eval harness will read the labels and resolve problem text from
    # whichever source matches `source` field. The tree problems file
    # is the only authored set.
    cohort_problems = OUT / "problems_cohort.jsonl"
    with cohort_problems.open("w") as f:
        for r in tree_problems:
            f.write(json.dumps(r) + "\n")
    print(f"wrote: {cohort_problems.relative_to(ROOT)}  (tree-problems n={len(tree_problems)})")
    print(f"       (LCB problems live in data/problems_lcb.jsonl + data/problems_lcb_hard.jsonl)")

    # 2x2 cell counts
    cells = defaultdict(list)
    for l in all_labels:
        cells[_bucket(l)].append(l)

    # Confidence breakdown
    high_count = sum(1 for l in all_labels
                     if l.get("irreducibility_confidence") == "high"
                     and l["reducibility_tier"] == "irreducible")
    med_count = sum(1 for l in all_labels
                    if l.get("irreducibility_confidence") == "medium"
                    and l["reducibility_tier"] == "irreducible")
    ineligible = [l["id"] for l in all_labels if not l.get("eligible_for_quadrant", True)]

    md = []
    md.append(f"# Merged cohort summary — {len(all_labels)} problems")
    md.append("")
    md.append(f"Generated by `src/build_merged_cohort.py`. Labels merged from "
              f"`labels_lcb_medium.jsonl`, `labels_lcb_hard.jsonl`, and `labels_trees.jsonl`.")
    md.append("")
    md.append("## 2×2 cell counts")
    md.append("")
    md.append("| | Array | Pointer | total |")
    md.append("|---|---:|---:|---:|")
    for red in ("reducible", "irreducible"):
        n_arr = len(cells[(red, "array")])
        n_ptr = len(cells[(red, "pointer")])
        md.append(f"| **{red.capitalize()}** | {n_arr} | {n_ptr} | {n_arr + n_ptr} |")
    total_arr = sum(len(cells[(r, "array")]) for r in ("reducible", "irreducible"))
    total_ptr = sum(len(cells[(r, "pointer")]) for r in ("reducible", "irreducible"))
    md.append(f"| **total** | {total_arr} | {total_ptr} | **{total_arr + total_ptr}** |")
    md.append("")

    md.append("## ≥ 8 floor check")
    md.append("")
    md.append("| cell | n | meets ≥ 8 |")
    md.append("|---|---:|:---:|")
    for red in ("reducible", "irreducible"):
        for rep in ("array", "pointer"):
            n = len(cells[(red, rep)])
            ok = "✓" if n >= 8 else "✗ STOP-AND-REPORT"
            md.append(f"| {red.capitalize()} × {rep.capitalize()} | {n} | {ok} |")
    md.append("")

    md.append("## Irreducibility confidence breakdown")
    md.append("")
    md.append(f"- `high`: {high_count}")
    md.append(f"- `medium`: {med_count}  (NOT silently in headline cells — reported separately)")
    med_ids = [l["id"] for l in all_labels if l.get("irreducibility_confidence") == "medium"]
    for x in med_ids:
        md.append(f"  - {x}")
    md.append("")

    md.append("## Quadrant eligibility")
    md.append("")
    md.append(f"- `eligible_for_quadrant = True`:  {len(all_labels) - len(ineligible)}")
    md.append(f"- `eligible_for_quadrant = False`: {len(ineligible)}  (Task 3 only — EXCLUDED from Task 4)")
    for x in ineligible:
        md.append(f"  - {x}")
    md.append("")

    # cell rosters
    md.append("## Cell rosters")
    md.append("")
    for red in ("irreducible", "reducible"):
        for rep in ("array", "pointer"):
            md.append(f"### {red.capitalize()} × {rep.capitalize()} (n = {len(cells[(red, rep)])})")
            md.append("")
            by_source = defaultdict(list)
            for l in cells[(red, rep)]:
                by_source[l["source"]].append(l)
            for src in sorted(by_source.keys()):
                md.append(f"- **{src}** ({len(by_source[src])}):")
                for l in by_source[src]:
                    flags = []
                    if l.get("irreducibility_confidence") == "medium":
                        flags.append("conf=med")
                    if not l.get("eligible_for_quadrant", True):
                        flags.append("Task3-only")
                    flag_str = f"  *[{', '.join(flags)}]*" if flags else ""
                    md.append(f"  - `{l['id']}` — {l.get('problem_class') or '(LCB)'}{flag_str}")
                md.append("")

    summary = OUT / "COHORT_SUMMARY.md"
    summary.write_text("\n".join(md) + "\n")
    print(f"wrote: {summary.relative_to(ROOT)}")

    # quick console print of the floor check
    print()
    print("=== ≥ 8 floor check ===")
    for red in ("reducible", "irreducible"):
        for rep in ("array", "pointer"):
            n = len(cells[(red, rep)])
            ok = "✓" if n >= 8 else "✗ STOP-AND-REPORT"
            print(f"  {red.capitalize():12s} × {rep.capitalize():7s}: n={n}  {ok}")


if __name__ == "__main__":
    main()
